name: Artefact Delete

on:
  push:
    branches:
      - artefact-delete-action

jobs:
  delete-artefacts:
    name: Delete Artefacts
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - name: Delete Artefacts
        uses: c-hive/gha-remove-artifacts@v1
        with:
          age: '1 minute'
