name: Build

on:
  push:
    branches:
      - ci-build-setup-v2

env:
  UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}

jobs:
  build:
    name: Build for ${{ matrix.targetPlatform }} on version ${{ matrix.unityVersion }}
    runs-on: ubuntu-latest
    timeout-minutes: 30
    strategy:
      matrix:
        projectPath:
          - Danki2
        unityVersion:
          - 2019.2.0f1
        targetPlatform:
          - StandaloneWindows64

    steps:
      - name: Checkout
        uses: actions/checkout@v2.1.0

      - name: Cache
        uses: actions/cache@v1.1.2
        with:
          path: ${{ matrix.projectPath }}/Library
          key: Library-${{ matrix.projectPath }}-${{ matrix.targetPlatform }}
          restore-keys: |
            Library-${{ matrix.projectPath }}-
            Library-

      - name: Build
        uses: webbertakken/unity-builder@v0.12
        with:
          projectPath: ${{ matrix.projectPath }}
          unityVersion: ${{ matrix.unityVersion }}
          targetPlatform: ${{ matrix.targetPlatform }}

      - name: Upload Artifacts
        uses: actions/upload-artifact@v1.0.0
        with:
          name: Build
          path: build
