# No Op workflow that will always pass. This is so that we can force branches to be up
# to date with master before getting merged. For some reason, GitHub requires an action
# to enable this setting.
# TODO: Remove this workflow when we have a more suitable action to run on pull_request
#       and update the settings in GutHub.

name: No Op

on:
  pull_request:
    branches:
      - master

jobs:
  no-op:
    name: No Op
    runs-on: ubuntu-latest
    steps:
      - name: Always Pass
        run: exit 0
