name: Schedule

on:
  schedule:
    - cron:  '*/1 * * * *'

jobs:
  schedule:
    name: Schedule test
    runs-on: ubuntu-latest
    timeout-minutes: 1

    steps:
      - name: Say hello
        run: echo hello
