name: Test

on:
  pull_request:
    branches:
      - master

env:
  UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}

jobs:
  test:
    name: Run Unity tests for ${{ matrix.targetPlatform }} on version ${{ matrix.unityVersion }}
    runs-on: ubuntu-latest
    timeout-minutes: 30
    strategy:
      matrix:
        projectPath:
          - Danki2
        unityVersion:
          - 2019.2.0f1
        targetPlatform:
          - StandaloneWindows64

    steps:
      - name: Checkout
        uses: actions/checkout@v2.1.0

      - name: Cache
        uses: actions/cache@v1.1.2
        with:
          path: ${{ matrix.projectPath }}/Library
          key: Library-${{ matrix.projectPath }}-${{ matrix.targetPlatform }}
          restore-keys: |
            Library-${{ matrix.projectPath }}-
            Library-

      - name: Test
        uses: webbertakken/unity-test-runner@v1.6
        with:
          projectPath: ${{ matrix.projectPath }}
          unityVersion: ${{ matrix.unityVersion }}
