# Validates that the project builds without errors, without saving the built projects as
# an artefact.
name: Validate Build

# Run on pull requests to master as we want to check that the game at least compiles before
# it can be merged into master.
# Disabled as it's annoying
# on:
#   pull_request:
#     branches:
#       - master
on:
  push:
    branches-ignore:
      - '**'

env:
  UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}

jobs:
  validate-build:
    name: Validate build for ${{ matrix.targetPlatform }} on version ${{ matrix.unityVersion }}
    runs-on: ubuntu-latest
    timeout-minutes: 40
    strategy:
      matrix:
        projectPath:
          - Danki2
        unityVersion:
          - 2019.2.0f1
        targetPlatform:
          - StandaloneWindows64

    steps:
      # Checkout the repository.
      - name: Checkout
        uses: actions/checkout@v2.1.0

      # GitHub cache, this will speed up subsequent runs of this workflow.
      - name: Cache
        uses: actions/cache@v1.1.2
        with:
          path: ${{ matrix.projectPath }}/Library
          key: Library-${{ matrix.projectPath }}-${{ matrix.targetPlatform }}
          restore-keys: |
            Library-${{ matrix.projectPath }}-
            Library-

      # Build the project with all combinations of the target platforms and unity versions
      # in the matrix defined above.
      - name: Validate Build
        uses: webbertakken/unity-builder@v0.12
        with:
          projectPath: ${{ matrix.projectPath }}
          unityVersion: ${{ matrix.unityVersion }}
          targetPlatform: ${{ matrix.targetPlatform }}
